# .forge-lock.hcl — DO NOT EDIT MANUALLY
# Generated by forge. Changes will be overwritten on sync.

blueprint {
  registry_url = "/Users/donaldgifford/code/forge-registry"
  name         = "go-docker"
  path         = "go/docker"
}

created_at    = "2026-06-29T09:12:16.265299Z"
last_synced   = "2026-06-29T09:12:16.265299Z"
forge_version = "0.7.0"

variables {
  git_host               = "github.com"
  git_provider           = "github"
  go_version             = "1.26.4"
  license                = "Apache-2.0"
  project_description    = "A Go API for docz repos"
  project_lifecycle      = "production"
  project_name           = "docz-api"
  project_org            = "donaldgifford"
  project_owner          = "donaldgifford"
  project_service        = "service"
  project_system         = "infrastructure"
  renovate_config_prefix = "github"
}

default ".checkmake.ini" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:123f1dc4a0f6e608cd57546d72894791ef719ad07cc0fdd53016d57557cb9284"
}

default ".claude/settings.json" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7fa2145b3bc9a192465144e24e2179d6062debdc730ea5012ef11a73982b2eb7"
}

default ".docz.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:f3fb2387d31e3b07fa2a1efdf3e974814b13113c763a7b82d7425eb2967bbcfc"
}

default ".github/labeler.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:d4f9c8e2a469a5b3849567391a695e80960de8962197ff8dacc57674cdc767f6"
}

default ".github/workflows/pr-labels.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9d0bbe7ec5e56ac192a21ed557d5dc700375c60b555a874bc22c05eb57bd86d4"
}

default ".gitignore" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:2ade0572a141b09f93c32c355d9f51a12f535feeb449979554e11c8fa0845a5a"
}

default ".makefmt.yml" {
  source   = "registry-default"
  strategy = "overwrite"
  hash     = "sha256:c56b8f4be0b7722a0e8fda97faf4d8c29e4ff75193acf663bf5a5b0e7fbf4808"
}

default ".markdownlint.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:46873f7070168a2258fc63e38db76c50e0c3bfb24c122864786900ec5f91d94a"
}

default ".prettierrc.yaml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:9f2bb9bb6b395c65c19b763d129f01b6a32ccfdea9bc46c040a9cfc683386b55"
}

default ".yamlfmt.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:5479bcd306bfb8108829c774651d94c344baec33e4592ff0472b8aa6693a8132"
}

default ".yamllint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:58da16ddd1b296be37d3d5bf3b3eee8500c652a9ac59b18675c854a7c63b4465"
}

default ".codecov.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:61c453beec7fb0701c025e1f01b8b530aceba409777155d6497f44d48f24ee8b"
}

default ".github/CODEOWNERS" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:666453f28d6c351868d33031fd710f5ebab775b7dab797694b23eb587e161a4a"
}

default ".github/actionlint.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8d5a2d594e5f08f6b57a814830c9511b1c3c6cb3d1341bc5295e2638f20bd884"
}

default ".github/dependabot.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:fab1e36ffa6b905e0c7ee83fab4435688aa3636ad7bde4dfacd7e0fe3fdf2828"
}

default ".github/licenses-csv.tpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:181b0c267bcc0c99b7e448de827c3a9a6c65ac4e2755d2529b9985018929b2f7"
}

default ".github/workflows/changelog-regen.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:94f93e1ce75a0738ee5930433f211593d8a0b3704c7499ba2d3f1a63695f5656"
}

default ".github/workflows/changelog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:77fc855332e849f8f08ab78aff325329f81a406a66cdddd5faac703ac7f90304"
}

default ".github/workflows/ci.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:a5188c3c1ab1ed1ad4a6f0946c77c20d6fbaa9552d33eb94d116ac8978276fa1"
}

default ".github/workflows/codeql.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:7d7ec516e1a4f643c5c9a628131fdab368291d98d4cd22bb61b943789ddcadd2"
}

default ".github/workflows/dependabot-severity-label.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:ebc9d498c6931a6eb93bcf05915b66f29267635d5ac02514e7964d7da3885aa1"
}

default ".github/workflows/license-check.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:4671b90741cc743c3b6bc8d9b6fe132dd1ad4bb2599344c9ebcb2ae62368c106"
}

default ".github/workflows/release.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:8020958cbb53657256a00111eeebc184f30c4cbf2466b90abb04464a10930729"
}

default ".github/workflows/security.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:752a8906470e7275e66dfea2985879d67f0258d29f0bd308fd73fb6899c12ded"
}

default ".github/workflows/trufflehog.yml" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:c5b0b27a968be616c41cb318b529732ed4a9558913d490fbbfea2d11e6d71bec"
}

default ".golangci.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:a7ac48bb43811344d0931c7dc127bf99484d9888b1eadb96fe9a472dea90e9e8"
}

default ".goreleaser.yml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:a3f665c8ad4551252673765128b1ef14cafe7ec9166d3be23e22a073eee8b88a"
}

default "CHANGELOG.md" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:b64a7868c1db77e87d899af1d46c8c12d19a8c39d0b3b9a43753f75c1a0718aa"
}

default "CLAUDE.md.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:3cf62e13ac21dd1b5f7f05c284d620933978ec721e27bfbbc26b3605d1f4c948"
}

default "Makefile.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:695133eb1d20ee8b82de20ad3679f2c798fdfd65a14b0deb0528a27ad5821cd4"
}

default "README.md.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:739f5816a7c9fae1d80a48af92007faefb95b53e30d078ccac133666ea4d5169"
}

default "catalog-info.yaml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:6f397fc3e3b1ffbd375e168d43d7295259fb86d3da96d5182a68c0056066d8a6"
}

default "cliff.toml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:df422b949a5e814ec95906fba4e0c2da9140f41ee024f3b261e6287045e68a41"
}

default "cmd/$${project_name}/main.go.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
}

default "go.mod.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:5c7bd1e0b7e4e78500956471ad990755c12211d1ffe3507b64f567c39c0e3963"
}

default "internal/.gitkeep" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}

default "justfile.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:35e2b788a679841d98d70dee0aefea2048cbf8d486e82c6c4d02c0681abf5625"
}

default "mise.toml.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:ebef4b1d1051b8eb2215901b984b45e232b0061491cd896729e3f4dbcd30d988"
}

default "renovate.json5.tmpl" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:15f4007ddcaa61259c275a55d0587b73d610f7a7e1bab6351518c61c962e280a"
}

default "scripts/labels.sh" {
  source   = "category-default"
  strategy = "overwrite"
  hash     = "sha256:37dead1ff5c5babd978afa02f4a8ac0ddd24396378b6f12cfeb808085accdcb8"
}
