// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package store

import (
	"context"
)

const recordDelivery = `-- name: RecordDelivery :one
INSERT INTO webhook_deliveries (delivery_id, event)
VALUES ($1, $2)
ON CONFLICT (delivery_id) DO NOTHING
RETURNING delivery_id
`

type RecordDeliveryParams struct {
	DeliveryID string `json:"delivery_id"`
	Event      string `json:"event"`
}

// Records a webhook delivery for idempotency. ON CONFLICT DO NOTHING means a
// replayed X-GitHub-Delivery inserts nothing and returns no row (pgx.ErrNoRows),
// which the store maps to isNew=false so the handler treats it as a no-op.
func (q *Queries) RecordDelivery(ctx context.Context, arg RecordDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, recordDelivery, arg.DeliveryID, arg.Event)
	var delivery_id string
	err := row.Scan(&delivery_id)
	return delivery_id, err
}
