// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doc_types.sql

package store

import (
	"context"
	"encoding/json"
)

const deleteDocType = `-- name: DeleteDocType :exec
DELETE FROM doc_types WHERE repo_id = $1 AND name = $2
`

type DeleteDocTypeParams struct {
	RepoID int64  `json:"repo_id"`
	Name   string `json:"name"`
}

func (q *Queries) DeleteDocType(ctx context.Context, arg DeleteDocTypeParams) error {
	_, err := q.db.Exec(ctx, deleteDocType, arg.RepoID, arg.Name)
	return err
}

const listDocTypes = `-- name: ListDocTypes :many
SELECT id, repo_id, name, dir, id_prefix, plural_label, statuses, aliases
FROM doc_types
WHERE repo_id = $1
`

func (q *Queries) ListDocTypes(ctx context.Context, repoID int64) ([]DocType, error) {
	rows, err := q.db.Query(ctx, listDocTypes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocType{}
	for rows.Next() {
		var i DocType
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Name,
			&i.Dir,
			&i.IDPrefix,
			&i.PluralLabel,
			&i.Statuses,
			&i.Aliases,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocType = `-- name: UpsertDocType :exec
INSERT INTO doc_types (repo_id, name, dir, id_prefix, plural_label, statuses, aliases)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (repo_id, name) DO UPDATE SET
    dir          = EXCLUDED.dir,
    id_prefix    = EXCLUDED.id_prefix,
    plural_label = EXCLUDED.plural_label,
    statuses     = EXCLUDED.statuses,
    aliases      = EXCLUDED.aliases
`

type UpsertDocTypeParams struct {
	RepoID      int64           `json:"repo_id"`
	Name        string          `json:"name"`
	Dir         string          `json:"dir"`
	IDPrefix    string          `json:"id_prefix"`
	PluralLabel string          `json:"plural_label"`
	Statuses    json.RawMessage `json:"statuses"`
	Aliases     json.RawMessage `json:"aliases"`
}

func (q *Queries) UpsertDocType(ctx context.Context, arg UpsertDocTypeParams) error {
	_, err := q.db.Exec(ctx, upsertDocType,
		arg.RepoID,
		arg.Name,
		arg.Dir,
		arg.IDPrefix,
		arg.PluralLabel,
		arg.Statuses,
		arg.Aliases,
	)
	return err
}
