// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE repo_id = $1 AND doc_id = $2
`

type DeleteDocumentParams struct {
	RepoID int64  `json:"repo_id"`
	DocID  string `json:"doc_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument, arg.RepoID, arg.DocID)
	return err
}

const listDocumentHashes = `-- name: ListDocumentHashes :many
SELECT doc_id, content_hash FROM documents WHERE repo_id = $1
`

type ListDocumentHashesRow struct {
	DocID       string `json:"doc_id"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) ListDocumentHashes(ctx context.Context, repoID int64) ([]ListDocumentHashesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentHashes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentHashesRow{}
	for rows.Next() {
		var i ListDocumentHashesRow
		if err := rows.Scan(&i.DocID, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (
    repo_id, type, doc_id, title, status, author, created,
    path, git_sha, content_hash, raw_md, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now()
)
ON CONFLICT (repo_id, doc_id) DO UPDATE SET
    type         = EXCLUDED.type,
    title        = EXCLUDED.title,
    status       = EXCLUDED.status,
    author       = EXCLUDED.author,
    created      = EXCLUDED.created,
    path         = EXCLUDED.path,
    git_sha      = EXCLUDED.git_sha,
    content_hash = EXCLUDED.content_hash,
    raw_md       = EXCLUDED.raw_md,
    updated_at   = now()
`

type UpsertDocumentParams struct {
	RepoID      int64       `json:"repo_id"`
	Type        string      `json:"type"`
	DocID       string      `json:"doc_id"`
	Title       string      `json:"title"`
	Status      pgtype.Text `json:"status"`
	Author      pgtype.Text `json:"author"`
	Created     pgtype.Date `json:"created"`
	Path        string      `json:"path"`
	GitSha      string      `json:"git_sha"`
	ContentHash string      `json:"content_hash"`
	RawMd       string      `json:"raw_md"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertDocument,
		arg.RepoID,
		arg.Type,
		arg.DocID,
		arg.Title,
		arg.Status,
		arg.Author,
		arg.Created,
		arg.Path,
		arg.GitSha,
		arg.ContentHash,
		arg.RawMd,
	)
	return err
}
