// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installations.sql

package store

import (
	"context"
)

const deleteInstallation = `-- name: DeleteInstallation :exec
DELETE FROM installations WHERE id = $1
`

// Removes an installation; ON DELETE CASCADE on repos wipes every subordinate
// repo, doc_type, and document. Used to offboard on app uninstall.
func (q *Queries) DeleteInstallation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInstallation, id)
	return err
}

const getInstallation = `-- name: GetInstallation :one
SELECT id, account_login, account_type, created_at, updated_at FROM installations WHERE id = $1
`

func (q *Queries) GetInstallation(ctx context.Context, id int64) (Installation, error) {
	row := q.db.QueryRow(ctx, getInstallation, id)
	var i Installation
	err := row.Scan(
		&i.ID,
		&i.AccountLogin,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInstallation = `-- name: UpsertInstallation :exec
INSERT INTO installations (id, account_login, account_type)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    account_login = EXCLUDED.account_login,
    account_type  = EXCLUDED.account_type,
    updated_at    = now()
`

type UpsertInstallationParams struct {
	ID           int64  `json:"id"`
	AccountLogin string `json:"account_login"`
	AccountType  string `json:"account_type"`
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) error {
	_, err := q.db.Exec(ctx, upsertInstallation, arg.ID, arg.AccountLogin, arg.AccountType)
	return err
}
