// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type DocType struct {
	ID          int64           `json:"id"`
	RepoID      int64           `json:"repo_id"`
	Name        string          `json:"name"`
	Dir         string          `json:"dir"`
	IDPrefix    string          `json:"id_prefix"`
	PluralLabel string          `json:"plural_label"`
	Statuses    json.RawMessage `json:"statuses"`
	Aliases     json.RawMessage `json:"aliases"`
}

type Document struct {
	ID          int64              `json:"id"`
	RepoID      int64              `json:"repo_id"`
	Type        string             `json:"type"`
	DocID       string             `json:"doc_id"`
	Title       string             `json:"title"`
	Status      pgtype.Text        `json:"status"`
	Author      pgtype.Text        `json:"author"`
	Created     pgtype.Date        `json:"created"`
	Path        string             `json:"path"`
	GitSha      string             `json:"git_sha"`
	ContentHash string             `json:"content_hash"`
	RawMd       string             `json:"raw_md"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Installation struct {
	ID           int64              `json:"id"`
	AccountLogin string             `json:"account_login"`
	AccountType  string             `json:"account_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Repo struct {
	ID             int64              `json:"id"`
	InstallationID int64              `json:"installation_id"`
	Owner          string             `json:"owner"`
	Name           string             `json:"name"`
	DefaultBranch  string             `json:"default_branch"`
	DocsDir        string             `json:"docs_dir"`
	ConfigSnapshot json.RawMessage    `json:"config_snapshot"`
	LastSyncedSha  pgtype.Text        `json:"last_synced_sha"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
	ChangelogMd    pgtype.Text        `json:"changelog_md"`
	ChangelogSha   pgtype.Text        `json:"changelog_sha"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	Email     pgtype.Text        `json:"email"`
	Login     pgtype.Text        `json:"login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	DeliveryID string             `json:"delivery_id"`
	Event      string             `json:"event"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}
