// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRepoPage = `-- name: DeleteRepoPage :exec
DELETE FROM repo_pages WHERE repo_id = $1 AND path = $2
`

type DeleteRepoPageParams struct {
	RepoID int64  `json:"repo_id"`
	Path   string `json:"path"`
}

func (q *Queries) DeleteRepoPage(ctx context.Context, arg DeleteRepoPageParams) error {
	_, err := q.db.Exec(ctx, deleteRepoPage, arg.RepoID, arg.Path)
	return err
}

const getRepoPageByPath = `-- name: GetRepoPageByPath :one
SELECT id, repo_id, path, repo_path, title, git_sha, content_hash, raw_md, updated_at FROM repo_pages WHERE repo_id = $1 AND path = $2
`

type GetRepoPageByPathParams struct {
	RepoID int64  `json:"repo_id"`
	Path   string `json:"path"`
}

// Full row including raw_md for the single-page endpoint. The match is
// exact-byte on the stored published path — no case folding (DESIGN-0004).
func (q *Queries) GetRepoPageByPath(ctx context.Context, arg GetRepoPageByPathParams) (RepoPage, error) {
	row := q.db.QueryRow(ctx, getRepoPageByPath, arg.RepoID, arg.Path)
	var i RepoPage
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Path,
		&i.RepoPath,
		&i.Title,
		&i.GitSha,
		&i.ContentHash,
		&i.RawMd,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepoPageHashes = `-- name: ListRepoPageHashes :many
SELECT path, content_hash FROM repo_pages WHERE repo_id = $1
`

type ListRepoPageHashesRow struct {
	Path        string `json:"path"`
	ContentHash string `json:"content_hash"`
}

// The reconcile's content-hash gate read: which pages exist and what
// content they carry.
func (q *Queries) ListRepoPageHashes(ctx context.Context, repoID int64) ([]ListRepoPageHashesRow, error) {
	rows, err := q.db.Query(ctx, listRepoPageHashes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoPageHashesRow{}
	for rows.Next() {
		var i ListRepoPageHashesRow
		if err := rows.Scan(&i.Path, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoPages = `-- name: ListRepoPages :many
SELECT id, repo_id, path, repo_path, title, git_sha, content_hash, updated_at
FROM repo_pages
WHERE repo_id = $1
ORDER BY path
`

type ListRepoPagesRow struct {
	ID          int64              `json:"id"`
	RepoID      int64              `json:"repo_id"`
	Path        string             `json:"path"`
	RepoPath    string             `json:"repo_path"`
	Title       string             `json:"title"`
	GitSha      string             `json:"git_sha"`
	ContentHash string             `json:"content_hash"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Metadata only (no raw_md) for the list endpoint, ordered by the
// published path.
func (q *Queries) ListRepoPages(ctx context.Context, repoID int64) ([]ListRepoPagesRow, error) {
	rows, err := q.db.Query(ctx, listRepoPages, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRepoPagesRow{}
	for rows.Next() {
		var i ListRepoPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Path,
			&i.RepoPath,
			&i.Title,
			&i.GitSha,
			&i.ContentHash,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepoPage = `-- name: UpsertRepoPage :exec
INSERT INTO repo_pages (
    repo_id, path, repo_path, title, git_sha, content_hash, raw_md, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now()
)
ON CONFLICT (repo_id, path) DO UPDATE SET
    repo_path    = EXCLUDED.repo_path,
    title        = EXCLUDED.title,
    git_sha      = EXCLUDED.git_sha,
    content_hash = EXCLUDED.content_hash,
    raw_md       = EXCLUDED.raw_md,
    updated_at   = now()
`

type UpsertRepoPageParams struct {
	RepoID      int64  `json:"repo_id"`
	Path        string `json:"path"`
	RepoPath    string `json:"repo_path"`
	Title       string `json:"title"`
	GitSha      string `json:"git_sha"`
	ContentHash string `json:"content_hash"`
	RawMd       string `json:"raw_md"`
}

func (q *Queries) UpsertRepoPage(ctx context.Context, arg UpsertRepoPageParams) error {
	_, err := q.db.Exec(ctx, upsertRepoPage,
		arg.RepoID,
		arg.Path,
		arg.RepoPath,
		arg.Title,
		arg.GitSha,
		arg.ContentHash,
		arg.RawMd,
	)
	return err
}
