// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRepoByOwnerName = `-- name: DeleteRepoByOwnerName :one
DELETE FROM repos WHERE owner = $1 AND name = $2 RETURNING id
`

type DeleteRepoByOwnerNameParams struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

// Removes one repo (CASCADE wipes its doc_types + documents) and returns its id
// so the caller can purge the same repo's documents from the search index.
func (q *Queries) DeleteRepoByOwnerName(ctx context.Context, arg DeleteRepoByOwnerNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteRepoByOwnerName, arg.Owner, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRepoByOwnerName = `-- name: GetRepoByOwnerName :one
SELECT id, installation_id, owner, name, default_branch, docs_dir, config_snapshot, last_synced_sha, last_synced_at, changelog_md, changelog_sha, created_at, updated_at, index_md, index_sha FROM repos WHERE owner = $1 AND name = $2
`

type GetRepoByOwnerNameParams struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

func (q *Queries) GetRepoByOwnerName(ctx context.Context, arg GetRepoByOwnerNameParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByOwnerName, arg.Owner, arg.Name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.DocsDir,
		&i.ConfigSnapshot,
		&i.LastSyncedSha,
		&i.LastSyncedAt,
		&i.ChangelogMd,
		&i.ChangelogSha,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IndexMd,
		&i.IndexSha,
	)
	return i, err
}

const listRepoIDsByInstallation = `-- name: ListRepoIDsByInstallation :many
SELECT id FROM repos WHERE installation_id = $1
`

// Repo ids under an installation, collected before DeleteInstallation removes
// the rows so the search index can be purged for each.
func (q *Queries) ListRepoIDsByInstallation(ctx context.Context, installationID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listRepoIDsByInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT id, installation_id, owner, name, default_branch, docs_dir, config_snapshot, last_synced_sha, last_synced_at, changelog_md, changelog_sha, created_at, updated_at, index_md, index_sha FROM repos ORDER BY owner, name
`

func (q *Queries) ListRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.DocsDir,
			&i.ConfigSnapshot,
			&i.LastSyncedSha,
			&i.LastSyncedAt,
			&i.ChangelogMd,
			&i.ChangelogSha,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IndexMd,
			&i.IndexSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repos (
    installation_id, owner, name, default_branch, docs_dir, config_snapshot,
    last_synced_sha, last_synced_at, changelog_md, changelog_sha,
    index_md, index_sha, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now(), $8, $9, $10, $11, now()
)
ON CONFLICT (owner, name) DO UPDATE SET
    installation_id = EXCLUDED.installation_id,
    default_branch  = EXCLUDED.default_branch,
    docs_dir        = EXCLUDED.docs_dir,
    config_snapshot = EXCLUDED.config_snapshot,
    last_synced_sha = EXCLUDED.last_synced_sha,
    last_synced_at  = now(),
    changelog_md    = EXCLUDED.changelog_md,
    changelog_sha   = EXCLUDED.changelog_sha,
    index_md        = EXCLUDED.index_md,
    index_sha       = EXCLUDED.index_sha,
    updated_at      = now()
RETURNING id
`

type UpsertRepoParams struct {
	InstallationID int64           `json:"installation_id"`
	Owner          string          `json:"owner"`
	Name           string          `json:"name"`
	DefaultBranch  string          `json:"default_branch"`
	DocsDir        string          `json:"docs_dir"`
	ConfigSnapshot json.RawMessage `json:"config_snapshot"`
	LastSyncedSha  pgtype.Text     `json:"last_synced_sha"`
	ChangelogMd    pgtype.Text     `json:"changelog_md"`
	ChangelogSha   pgtype.Text     `json:"changelog_sha"`
	IndexMd        pgtype.Text     `json:"index_md"`
	IndexSha       pgtype.Text     `json:"index_sha"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRepo,
		arg.InstallationID,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.DocsDir,
		arg.ConfigSnapshot,
		arg.LastSyncedSha,
		arg.ChangelogMd,
		arg.ChangelogSha,
		arg.IndexMd,
		arg.IndexSha,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
