// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoByOwnerName = `-- name: GetRepoByOwnerName :one
SELECT id, installation_id, owner, name, default_branch, docs_dir, config_snapshot, last_synced_sha, last_synced_at, changelog_md, changelog_sha, created_at, updated_at FROM repos WHERE owner = $1 AND name = $2
`

type GetRepoByOwnerNameParams struct {
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

func (q *Queries) GetRepoByOwnerName(ctx context.Context, arg GetRepoByOwnerNameParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByOwnerName, arg.Owner, arg.Name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.DocsDir,
		&i.ConfigSnapshot,
		&i.LastSyncedSha,
		&i.LastSyncedAt,
		&i.ChangelogMd,
		&i.ChangelogSha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repos (
    installation_id, owner, name, default_branch, docs_dir, config_snapshot,
    last_synced_sha, last_synced_at, changelog_md, changelog_sha, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now(), $8, $9, now()
)
ON CONFLICT (owner, name) DO UPDATE SET
    installation_id = EXCLUDED.installation_id,
    default_branch  = EXCLUDED.default_branch,
    docs_dir        = EXCLUDED.docs_dir,
    config_snapshot = EXCLUDED.config_snapshot,
    last_synced_sha = EXCLUDED.last_synced_sha,
    last_synced_at  = now(),
    changelog_md    = EXCLUDED.changelog_md,
    changelog_sha   = EXCLUDED.changelog_sha,
    updated_at      = now()
RETURNING id
`

type UpsertRepoParams struct {
	InstallationID int64           `json:"installation_id"`
	Owner          string          `json:"owner"`
	Name           string          `json:"name"`
	DefaultBranch  string          `json:"default_branch"`
	DocsDir        string          `json:"docs_dir"`
	ConfigSnapshot json.RawMessage `json:"config_snapshot"`
	LastSyncedSha  pgtype.Text     `json:"last_synced_sha"`
	ChangelogMd    pgtype.Text     `json:"changelog_md"`
	ChangelogSha   pgtype.Text     `json:"changelog_sha"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRepo,
		arg.InstallationID,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.DocsDir,
		arg.ConfigSnapshot,
		arg.LastSyncedSha,
		arg.ChangelogMd,
		arg.ChangelogSha,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
