// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (provider, subject, email, login)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider, subject) DO UPDATE SET
    email = EXCLUDED.email,
    login = EXCLUDED.login
RETURNING id
`

type UpsertUserParams struct {
	Provider string      `json:"provider"`
	Subject  string      `json:"subject"`
	Email    pgtype.Text `json:"email"`
	Login    pgtype.Text `json:"login"`
}

// Creates or updates the durable user row for a provider identity, refreshing
// the email/login on each login. Sessions live in Redis, not here; this row is
// the audit record of who has logged in. Returns the user id.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Provider,
		arg.Subject,
		arg.Email,
		arg.Login,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
